/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux itops-X8DA6 4.10.0-35-generic x86_64"
#define LGL_COMPILED "Thu Oct  5 17:48:12 +04 2017"
#define LGL_RELEASED "Don Mai 22 22:08:00 CEST 2014"
#define LGL_VERSION "azf"
#define LGL_ID "92032848c138b2f33629ad24394d60a3787a1046"
